name: Publish-CI

on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint check
        uses: azohra/shell-linter@v0.4.0    

  release:

    runs-on: ubuntu-latest

    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Release new version
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false        